// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4lxR4LAMGtRTx4xhtCjNBOKrHVdx9woA',
    appId: '1:295910566687:web:f9e9a205b78815950d5e2a',
    messagingSenderId: '295910566687',
    projectId: 'jarvis-592cf',
    authDomain: 'jarvis-592cf.firebaseapp.com',
    databaseURL: 'https://jarvis-592cf-default-rtdb.firebaseio.com',
    storageBucket: 'jarvis-592cf.appspot.com',
    measurementId: 'G-2E89XF8GTG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKgNEpyvpM7te58vWeQ1486znwT6RdFpQ',
    appId: '1:295910566687:android:d3238871b73b5e750d5e2a',
    messagingSenderId: '295910566687',
    projectId: 'jarvis-592cf',
    databaseURL: 'https://jarvis-592cf-default-rtdb.firebaseio.com',
    storageBucket: 'jarvis-592cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAabEO_qClqRHiQ-9N-smQgbND8C-OwYIA',
    appId: '1:295910566687:ios:408f543ab5cd7c280d5e2a',
    messagingSenderId: '295910566687',
    projectId: 'jarvis-592cf',
    databaseURL: 'https://jarvis-592cf-default-rtdb.firebaseio.com',
    storageBucket: 'jarvis-592cf.appspot.com',
    iosClientId: '295910566687-s0k4i1glkk09g2phqbejt44lcicd9hlm.apps.googleusercontent.com',
    iosBundleId: 'com.cumawa.jarvis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAabEO_qClqRHiQ-9N-smQgbND8C-OwYIA',
    appId: '1:295910566687:ios:408f543ab5cd7c280d5e2a',
    messagingSenderId: '295910566687',
    projectId: 'jarvis-592cf',
    databaseURL: 'https://jarvis-592cf-default-rtdb.firebaseio.com',
    storageBucket: 'jarvis-592cf.appspot.com',
    iosClientId: '295910566687-s0k4i1glkk09g2phqbejt44lcicd9hlm.apps.googleusercontent.com',
    iosBundleId: 'com.cumawa.jarvis',
  );
}
